package farto.cleva.guilherme.main;

import farto.cleva.guilherme.bo.JsonXmlParser;
import farto.cleva.guilherme.utils.FileUtil;

public class MainAsString {

	public static void main(String[] args) {

		StringBuilder json = new StringBuilder("");

		json.append("{");
		json.append("	\"resultado\": {");
		json.append("		\"dataExecucao\": \"30/05/2017 09:25:27\",");
		json.append("		\"registros\": [{");
		json.append("			\"colunasVO\": [{");
		json.append("				\"codigo\": \"CD_FORNEC\",");
		json.append("				\"descricao\": \"Fornecedor\",");
		json.append("				\"fgTipo\": \"C\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"E\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"C\",");
		json.append("					\"valor\": \"123 - GUILHERME FARTO\"");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 0");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"CD_UPNIVEL1\",");
		json.append("				\"descricao\": \"Fazenda\",");
		json.append("				\"fgTipo\": \"C\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"E\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"C\",");
		json.append("					\"valor\": \"  1234 - GUILHERME FARTO E OUTROS\"");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 140");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"DISTANCIA\",");
		json.append("				\"descricao\": \"Distância\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,##0.0\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 35.3");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"TC\",");
		json.append("				\"descricao\": \"Ton\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"###,###,##0.000\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 178265.22");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 0");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"PC_CANA\",");
		json.append("				\"descricao\": \"% Cana\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"##0.00\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 100");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"CARGA_ENT\",");
		json.append("				\"descricao\": \"Cargas Ent\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,###,##0\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 8918");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 0");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"CARGA_ANL\",");
		json.append("				\"descricao\": \"Cargas Anl\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,###,##0\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 8527");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 0");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"PERC_CANA_ANL\",");
		json.append("				\"descricao\": \"% Anl\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"##0.0\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 95.1");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"DENS_CARGA\",");
		json.append("				\"descricao\": \"Dens\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,###,##0.000\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 19.989");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"BRIX\",");
		json.append("				\"descricao\": \"Brix\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,###.00\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 19.09");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"POL\",");
		json.append("				\"descricao\": \"Pol\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,##0.00\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 16.59");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"PUREZA\",");
		json.append("				\"descricao\": \"Pza\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,###.00\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 86.9");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"AR\",");
		json.append("				\"descricao\": \"Ar\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,##0.00\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 0.55");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"PC\",");
		json.append("				\"descricao\": \"PC\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,##0.00\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 13.77");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"FIBRA\",");
		json.append("				\"descricao\": \"Fibra\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,##0.00\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 13.15");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"AR_CALC\",");
		json.append("				\"descricao\": \"AR Calc\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,##0.00\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 0.55");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"ATR\",");
		json.append("				\"descricao\": \"ATR\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"##0.00\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 137.66");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"TMP\",");
		json.append("				\"descricao\": \"TMP\",");
		json.append("				\"fgTipo\": \"C\",");
		json.append("				\"mascara\": \"#,##0.0\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"C\",");
		json.append("					\"valor\": \"20.7\"");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"IMP\",");
		json.append("				\"descricao\": \"Imp\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,##0.00\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 1.31");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			},");
		json.append("			{");
		json.append("				\"codigo\": \"PERC_BROCA\",");
		json.append("				\"descricao\": \"% Broca\",");
		json.append("				\"fgTipo\": \"N\",");
		json.append("				\"mascara\": \"#,##0.00\",");
		json.append("				\"corFonte\": \"000000\",");
		json.append("				\"tamanhoFonte\": 8,");
		json.append("				\"fgAlinhamento\": \"D\",");
		json.append("				\"valor\": {");
		json.append("					\"fgTipo\": \"N\",");
		json.append("					\"valor\": 0.14");
		json.append("				},");
		json.append("				\"tamanhoColRelatorio\": 50,");
		json.append("				\"fgNegrito\": false,");
		json.append("				\"fgItalico\": false,");
		json.append("				\"fgSublinhado\": false,");
		json.append("				\"fgTachado\": false,");
		json.append("				\"tamanhoCampo\": 40");
		json.append("			}],");
		json.append("			\"id\": \"6a38958b5397da99b51003cb775338ec\"");
		json.append("		}]");
		json.append("	},");
		json.append("	\"isTotalizador\": false,");
		json.append("	\"isTotalizadorGeral\": false,");
		json.append("	\"restIntegration\": false,");
		json.append("	\"isGerarPdf\": false,");
		json.append("	\"id\": \"2549bac0b192715d9cf887bb4f47dd09\"");
		json.append("}");

		try {
			// String xml = new JsonXmlParser().extract(FileUtil.createTempFile("temp-data.json", json.toString()));
			// String xml = new JsonXmlParser("data", "data-item").extract(FileUtil.createTempFile("temp-data.json", json.toString()));
			// String xml = new JsonXmlParser(true).extract(FileUtil.createTempFile("temp-data.json", json.toString()));
			// String xml = new JsonXmlParser("data", "data-item", true).extract(FileUtil.createTempFile("temp-data.json", json.toString()));

			String xml = new JsonXmlParser("data", "data-item", true).replaceTag("resultado/registros/colunasVO", "colunas").extract(FileUtil.createTempFile("temp-data.json", json.toString()));

			System.out.println(xml);
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

}
